In [2]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
import plotly.express as px
import pickle
from sklearn.metrics import roc_curve, auc, confusion_matrix
import seaborn.objects as so
import matplotlib.pyplot as plt

In [3]:
# importando dados
df = pd.read_csv('df_esteroids_MB_IN_AR.csv', sep = ';')
df.columns = df.columns.astype(str)
df.columns = ["".join(c if c.isalnum() else "_" for c in str(col)) for col in df.columns]
df

,Classe,__M__,__M_15__,_M_29__,_M_90__,_M_2_90__,_M_3_90_,_M_90_15__,_M_2_90_15__,_M_3_90_15_,...,_M_140_,_M_157_,_M_144_,m_z_103,m_z_129,m_z_143,m_z_169,m_z_244,_m_z_218,m_z_231
0,2,3,3,0,0,0,0,3,3,0,...,0,0,0,0,1,1,2,0,0,0
1,0,3,0,0,0,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,2,3,1,0,0,0,0,0,0,0,...,1,0,0,0,1,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,6,2,1,0,3,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
154,6,3,0,0,2,0,0,1,0,0,...,0,0,0,0,0,0,0,0,3,3
155,6,3,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
156,6,1,2,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
157,6,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [4]:
# separando variÃ¡veis descritoras
Xi = df.iloc[:,1::]
Xi

,__M__,__M_15__,_M_29__,_M_90__,_M_2_90__,_M_3_90_,_M_90_15__,_M_2_90_15__,_M_3_90_15_,_M_90_29__,...,_M_140_,_M_157_,_M_144_,m_z_103,m_z_129,m_z_143,m_z_169,m_z_244,_m_z_218,m_z_231
0,3,3,0,0,0,0,3,3,0,0,...,0,0,0,0,1,1,2,0,0,0
1,3,0,0,0,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,3,1,0,0,0,0,0,0,0,0,...,1,0,0,0,1,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,2,1,0,3,0,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
154,3,0,0,2,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,3,3
155,3,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
156,1,2,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
157,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [6]:
# variÃ¡vel target
# separando classe 0(nao-derivado de esteroide) e 1
from collections import Counter

# Supondo que df seja o seu DataFrame

# Inicializando uma nova coluna 'Classe_bin' com valor padrÃ£o 0
df['Classe_AAS'] = 0

# Atribuindo valor 1 para o intervalo [91:,:]
df.loc[92:, 'Classe_AAS'] = 1

# Exibindo as contagens apÃ³s a separaÃ§Ã£o
counter = Counter(df['Classe_AAS'])
y = df['Classe_AAS']
y = np.array(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1])

In [ ]:
# balanceando os dados 
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter

# Separando classe 0 (nÃ£o derivado de esteroide) e 1
y = np.where(df['Classe_AAS'].values == 0, 0, 1)
y = np.array(y)
y = y.ravel()
# Verificando a contagem inicial das classes
print("Contagem inicial das classes:", Counter(y))

# Aplicando UnderSampler usando RandomUnderSampler
rs = RandomUnderSampler(random_state=42)
xi_resampled, y_resampled = rs.fit_resample(Xi, y)

# Verificando a contagem apÃ³s o UnderSampler
print("Contagem apÃ³s UnderSampler:", Counter(y_resampled))